---
- name: Install Nginx
  apt:
    name: nginx 
    state: latest
 
- name: Copy config file
  template:
    src: "nginx.conf" 
    dest: "/etc/nginx/nginx.conf"
  notify:
    - Restart Nginx  

- name: Delete the default unnecessary files
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
   - "/etc/nginx/sites-enabled/default"
   - "/var/www/html/index.nginx-debian.html"
  notify:
    - Restart Nginx
